# Generated by Django 5.1.4 on 2025-01-15 12:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volonteer', '0002_remove_event_created_at_remove_event_total_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
