# Generated by Django 5.1.4 on 2025-01-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volonteer', '0005_user_profile_picture_user_profile_picture_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='achievements',
            field=models.ManyToManyField(blank=True, related_name='users', to='volonteer.achievement'),
        ),
    ]
