# Generated by Django 5.1.4 on 2025-01-19 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volonteer', '0006_achievement_user_achievements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='achievements',
        ),
        migrations.AddField(
            model_name='user',
            name='achievements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='volonteer.achievement'),
        ),
    ]
