# Generated by Django 5.1.4 on 2025-01-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volonteer', '0007_remove_user_achievements_user_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='criteria_hours',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='criteria_tasks',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='user',
            name='achievements',
        ),
        migrations.AddField(
            model_name='user',
            name='achievements',
            field=models.ManyToManyField(blank=True, related_name='users', to='volonteer.achievement'),
        ),
    ]
