# Generated by Django 5.1.4 on 2025-01-19 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volonteer', '0008_achievement_criteria_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='achievements',
        ),
        migrations.AddField(
            model_name='achievement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
    ]
