# Generated by Django 5.1.4 on 2025-01-19 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volonteer', '0009_remove_user_achievements_achievement_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='user',
        ),
        migrations.AddField(
            model_name='achievement',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='achievement_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='achievements',
            field=models.ManyToManyField(blank=True, related_name='user_achievements', to='volonteer.achievement'),
        ),
    ]
